version: "1"
rules:
  - base: master
    upstream: NateScarlet:master # change `wei` to the owner of upstream repo
    mergeMethod: merge # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
